### ISSUE TITLE
Publish audioservers to maven central

### ISSUE THREAD

**Issue by kullmanp** [jaudiolibs/audioservers#3]
I would like to use audioservers modules as dependencies in a maven build of beads. It would be great if you could publish them on maven central (same as with jnajack).

**Comment by neilcsmith-net** [comment]
Sure, I'll look at doing that soon.  Plan is to get all the JAudioLibs stuff up there at some point (JNAJack went up first as a test for GStreamer work I was doing).

Note that Beads is using deprecated functionality in the API - the AudioServer backend really needs a rewrite if you're going to push to Maven.  Happy to help out with that.

**Comment by neilcsmith-net** [comment]
This is finally done! Sorry for the massive delay.
