### ISSUE TITLE
Looking for a usable Java audio library

### ISSUE THREAD

**Issue by stefan-reich** [jaudiolibs/audioservers#4]
Hi, JavaSound on Linux is so broken as to be unusable. I'm looking for alternatives.

Installing JACK is too much of a hassle. Library should work with PulseAudio.

Can you help?

**Comment by neilcsmith-net** [comment]
Hi! What OS / version are you on?  What JDK?

In general, JavaSound on Linux works better than anywhere else, and OpenJDK already has a PulseAudio backend.  Have you tried the JavaSound AudioServer?  The idea of this is to provide a float buffer based callback API on top of JavaSound, so might make things better for you?  If you have a particular problem or find something particularly lacking with that please file a specific issue.

There's an old blog post about the API here that might be useful - https://praxisintermedia.wordpress.com/2013/11/06/jaudiolibs-audioservers-a-portaudio-esque-java-api/

I'm not averse to accepting a PR for a direct PulseAudio backed AudioServer, but am unlikely to write it myself.

Let me know how you get on. Thanks, Neil

**Comment by neilcsmith-net** [comment]
@stefan-reich closing this as heard nothing further from you.  Please re-open if need be.
